# Generated by Django 5.1.15 on 2026-03-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_therapist_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapist',
            name='county',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
